[package]
name = "discord_bot"
version = "0.1.0"
edition = "2024"

# DiscordBot
[dependencies.serenity]
default-features = false
features = [
    "builder",
    "chrono",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.12.4"

[dependencies]
# Discord

# AWS
# aws-config = { version = "1.5.16" }
# aws-sdk-ec2instanceconnect = { version = "1.58.0" }

# Other
tokio = { version = "1.43.0", features = ["full"] }
dotenv = { version = "0.15.0" }