[package]
name = "YOLO-ETC-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
dotenv = { version = "0.15.0" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
