name: test actions

on:
  push:
    branches: [ "master" ]
    paths: [ ./test/*.rs ]
  workflow_dispatch:

jobs:
  build:
    name: Rust toolchain build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: cations toolchainon
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          components: reutfmt, clippy

  test:
    name: Discord bot feture test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check 
